
version: "3.8"
services:

  jupyter:
    image: ghcr.io/marcelmaatkamp/mkdocs-material-jupyter:${MKDOCS_MATERIAL_VERSION}
    build:
      context: .
      args:
        MKDOCS_MATERIAL_VERSION: ${MKDOCS_MATERIAL_VERSION}
    # user: ${UID}:${GID}
    entrypoint: jupyter
    command: lab --ip 0.0.0.0 --no-browser --NotebookApp.token=''
    ports:
      - 8888:8888

  mkdocs:
    build:
      context: .
      args:
        MKDOCS_MATERIAL_VERSION: ${MKDOCS_MATERIAL_VERSION}
    command: gh-deploy
    ports:
      - 8000:8000
    volumes:
      - .:/home/jovyan/docs
      - ./mkdocs.yml:/home/jovyan/mkdocs.yml
      - ./README.md:/home/jovyan/docs/README.md
      - ./.git:/home/jovyan/.git
      - ~/.ssh/known_hosts:/home/jovyan/.ssh/known_hosts
      - ~/.ssh/id_rsa:/home/jovyan/.ssh/id_rsa:ro
